#!/bin/bash

activate () {
  . ../../../../venv/bin/activate
}
if [[ "$VIRTUAL_ENV" != "" ]]
then
  python ../../manage.py collectstatic
  yarn run build:clean && yarn run build:sass && yarn run build:postcss && yarn run build:cleancss
else
  activate
  python ../../manage.py collectstatic
  yarn run build:clean && yarn run build:sass && yarn run build:postcss && yarn run build:cleancss
  deactivate
fi
yarn dlx purgecss --css ../static/css/styles.css ../../staticfiles/css/*.css --content ../../templates/**/*.html --config postcss.config.js --output ../../staticfiles/css
