version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: sphinx-click
    versions:
    - 2.6.0
    - 2.7.0
  - dependency-name: pillow
    versions:
    - 8.1.1
    - 8.1.2
  - dependency-name: numpy
    versions:
    - 1.20.0
    - 1.20.1
  - dependency-name: pytest
    versions:
    - 6.2.2
