language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
jobs:
  allow_failures:
  - python: nightly
install:
  - pip install --upgrade pip
  - pip install poetry
script:
  - poetry install
  - poetry build
  - pytest tests/
