language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "3.10-dev"
jobs:
  allow_failures:
    - python: 3.9-dev
    - python: 3.10-dev
before_install:
  - docker build -t sumanthratna/viewmask .
  - docker run sumanthratna/viewmask /bin/sh -c "poetry run pytest tests/"
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install poetry
script:
  - poetry run python3 -m pip install "setuptools<45.3.0"
  - poetry install
  - poetry build
  - poetry run pytest tests/
