language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
jobs:
  allow_failures:
  - python: nightly
script:
  - pip install .
  - pip uninstall viewmask -y
  - pip install ".[collaborate]"
  - cd viewmask/viewmask-collaborate && python manage.py test
  # - pytest tests/
