name: Build Package and Run Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install poetry
        poetry install

    - name: Build Python package
      run: poetry build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Build Docker image
      run: docker build --tag "sumanthratna/viewmask:$GITHUB_SHA" .

    - name: Run tests
      run: |
        poetry run pytest tests/
        docker run "sumanthratna/viewmask:$GITHUB_SHA" /bin/sh -c "poetry run pytest tests/"
